### ISSUE TITLE
Duplicated warnings in console when quiet flag is set to false

### ISSUE THREAD

**Issue by sergesemashko** [JaKXz/stylelint-webpack-plugin#61] opened 2017-01-17 11:31 UTC
I noticed that warrnings are duplicated when quiet flag is set to false - http://take.ms/GQb4g.
I think, [this line](https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/run-compilation.js#L30) is the reason

**Comment by bellizio** [comment] 2017-01-17 13:48
I've just encountered this issue as well. Here is a screenshot:

<img width="461" alt="duplicate-output" src="https://cloud.githubusercontent.com/assets/2282499/22022813/8270b272-dc91-11e6-99e2-4550a8c98342.png">

Setting ```quiet: true``` removes the first output (in orange) and only shows the second output (in pink).

**Comment by JaKXz** [comment] 2017-01-17 21:26
@bellizio so if I understand correctly, we only want to see the second output (pink) if we have `quiet` set to anything but `false`? I have achieved this in #60 I believe, but I'm thinking that maybe this is not the behaviour that was intended for the `quiet` flag. I believe it's meant to suppress ALL of `stylelint`'s output in the webpack console, would you guys agree?

**Comment by JaKXz** [comment] 2017-01-17 23:16
@sergesemashko @bellizio this behaviour was brought back to this state in #51.

**Comment by rfgamaral** [comment] 2017-01-17 23:59
@JaKXz I'm also having this issue and I tried the `master` branch but I don't think the behavior is quite there... I have `failOnError: false` (which is the default), yet the build fails when we have CSS errors.

Given the screenshot above, the fix would be to remove the pink output (error, failing the build), not the orange one (just warnings, build is successful).

**Comment by sergesemashko** [comment] 2017-01-18 12:43
Duplicates are fixed in master branch. I would agree that `quiet: true` should suppress all message to console.

**Comment by bellizio** [comment] 2017-01-18 14:47
@JaKXz I think the first output (orange) should be removed. I tested the master branch and can confirm the duplicate outputs are gone now as a result of the latest merge. 

Also, I think it's worth noting that the severity of all stylelint rules is "error" by default as per the [docs](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#severities-error--warning). That being said, the first output (orange) in the screenshot I initially posted are errors, not warnings. 

As a test, I changed the severity of my indentation rule (on the master branch) to "warning". The output now looks like this:
<img width="462" alt="warning-output" src="https://cloud.githubusercontent.com/assets/2282499/22067961/62ef0702-dd61-11e6-87fc-e0280cf7c625.png">

However, if there are "errors" in addition to "warnings", the output is this:
<img width="581" alt="warning-error" src="https://cloud.githubusercontent.com/assets/2282499/22068335/ae55a5e2-dd62-11e6-9e4d-23816b0a3505.png">

Given that, I think the most recent changes to the eliminate the duplicate outputs are appropriate and make the most sense. But I'm not sure that the output when there errors and warnings is optimal.

Lastly, I am also in agreement that `quiet: true` should suppress both warnings and/or errors if there are any. Perhaps that should be addressed in a separate issue, though.

What does everyone think?

**Comment by cwonrails** [comment] 2017-01-24 15:49
Has anyone found a solution / have any input regarding @bellizio's comment in https://github.com/JaKXz/stylelint-webpack-plugin/issues/61#issuecomment-273494401?

**Comment by JaKXz** [comment] 2017-05-16 18:39
Is this still an issue for folks with v0.7?

**Comment by DorianGrey** [comment] 2017-05-30 06:53
It is.
Atm., the linter results are manually logged  [here](https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/run-compilation.js#L30), but they are also added as warnings or errors to the compilation results [here](https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/run-compilation.js#L42). Thus, they appear twice in case quiet is set to `false`.

When setting `quiet` to `true` or just leaving it out, the results are only added in the `after-emit` hook, which I'd expect to happen.

To be honest, I'm not sure if the `quiet` option is useful anyway - it does not make sense to add a linter to the process, but suppress its output.

**Comment by nass600** [comment] 2018-01-26 15:14
Any news about this? It is still happening in 0.10.1

**Comment by stevenleija** [comment] 2018-01-30 17:49
Any updates on this?  I'm working on our build scripts and would like to suppress the warning notifications during a production build and this appears to be the thread addressing this feature.

**Comment by JaKXz** [comment] 2018-01-31 00:05
I have opened a PR to address this, if anyone wants to look it over that would be great.

**Closed** 2018-02-15 01:55 UTC
Labels: bug

**Comment by JaKXz** [comment] 2018-02-15 01:58
`+ stylelint-webpack-plugin@0.10.2` has finally been published. Please kick the tires and let me know if you are still seeing this issue.

**Comment by nass600** [comment] 2018-02-22 08:17
Working for me, thanks @JaKXz

**Comment by bellizio** [comment] 2018-02-23 13:19
@JaKXz the duplicate warning/error output in the console is fixed for me as well after upgrading. 

What is the verdict on the `quiet` option? I see plugin still outputs an error log when the option is set to true.
