### ISSUE TITLE
Can't hide warnings

### ISSUE THREAD

**Issue by Teun87** [JaKXz/stylelint-webpack-plugin#80] opened 2017-04-24 13:59 UTC
I'm trying to hide the console warnings when in production:

        new StyleLintPlugin({
            files: 'craft/templates/**/*.?(s)?(a|c)ss',
            emitErrors: false,
            quiet: true
        })

All other options do work, but can't set quiet to 'true'. Any ideas or tips?

**Comment by JaKXz** [comment] 2017-05-08 00:50
@Teun87 I'm not sure what you mean by 

> can't set `quiet` to `true`

With v0.7, `quiet` is defaulted to true, so that results are not duplicated in the console. In fact the option should probably be renamed to `verbose` or something to better reflect it's function. 

Could you please provide an example repo (or the link to your project if OSS) and I'd love to be more helpful than this comment. Thanks!

**Comment by JaKXz** [comment] 2017-05-16 18:41
This also sounds like a duplicate of #61 so I'm going to close this in favour of that issue. Please feel free to reopen if I'm wrong.

**Closed by JaKXz** 2017-05-16 18:41 UTC
